better run-job

diff --git a/deploy/bin/run-job b/deploy/bin/run-job
--- a/deploy/bin/run-job
+++ b/deploy/bin/run-job
@@ -4,13 +4,6 @@ set -eou pipefail
 dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 tmp_dir='/tmp'
 
-# Prereqs
-case "$(uname -a)" in
-  *arm* )
-    deploy_dir='/usr/local/deploy/bin'
-    set +e; eval "${deploy_dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; ;; # set +e when apk not available
-esac
-
 get_artifact_from_aws(){
   aws s3 cp --profile skilbjo-robot s3://skilbjo/aeon.jar       "${dir}/app.jar"
 }
@@ -25,8 +18,16 @@ get_artifact_from_circle_ci(){
   curl "$artifact_url" >"${dir}/app.jar"
 }
 
+# Prereqs
 case "$(uname -a)" in
-  FreeBSD* )
+  *arm* )
+    deploy_dir='/usr/local/deploy/bin'
+    set +e; eval "${deploy_dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; # set +e when apk not available
+    mv /app.jar "${dir}/app.jar" ;;
+esac
+
+case "$(uname -a)" in
+  FreeBSD* | Darwin )
     # virtualbox is fucked in FreeBSD 11.2-RELEASE
     # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228535
     # Docker only runs natively on Linux (not BSD), so let's just run the jar
@@ -37,10 +38,8 @@ case "$(uname -a)" in
     if [[ -f ${dir}/app.jar ]];            then rm "${dir}/app.jar"; fi
     get_artifact_from_circle_ci
 
-    JAVA_OPTS="-Duser.timezone=UTC -Xms256m -Xmx512m -XX:MaxMetaspaceSize=128m"
-    cmd="java $JAVA_OPTS -jar ${dir}/app.jar"
-    ;;
-  * ) cmd="java $JAVA_OPTS -jar /app.jar" ;;
+    JAVA_OPTS="-Duser.timezone=UTC -Xms256m -Xmx512m -XX:MaxMetaspaceSize=128m" ;;
 esac
 
+cmd="java $JAVA_OPTS -jar ${dir}/app.jar"
 exec $cmd $@
